kind: Service
apiVersion: v1
metadata:
  name: html-openshift-appgithubaction
  labels:
    app: html-openshift-appgithubaction
    app.kubernetes.io/part-of: html-openshift-appgithubaction
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: html-openshift-appgithubaction